### ISSUE TITLE
Unable to Access Controller Constructor's Statements

### ISSUE THREAD

**Issue by SirBillofLane** [eNeRGy164/LivingDocumentation#58]
[analysis.txt](https://github.com/eNeRGy164/LivingDocumentation/files/12306046/analysis.txt)
How can I access the items in the Controller Statements? These items generally are the same as the constructor parameters. I sometimes add statements that are not constructor parameters. These are LivingDocumentation.InvocationDescription type. The BowlController is an example.

Thank you for LivingDocument is a huge asset. It solves my lack of documentation problem that a lot of developers experience. I am incorporating it in all my projects. I have to figure out how to document Razor pages, but that's a later task.
Bill

**Comment by eNeRGy164** [comment]
Hello and thank you for using LivingDocumentation for your project!

I appreciate your feedback and I'm here to help. From your description, I'm not entirely clear on the specific details you're seeking from the constructor. It's possible that not all the information you're looking for is being serialized.

To give you a bit more insight, if you navigate to line 3892 in the JSON file, you'll find the serialized details of the constructor. Here's a snippet of C# code that might help you retrieve the properties of the constructor:

```csharp
var type = Types.FirstOrDefault("MrPixter2019.Controllers.BowlController");
var parameters = type.Constructors[0].Parameters; 
var statements = type.Constructors[0].Statements;
```

From what I can see, there are 4 parameters, which I believe are values injected via dependency injection.

Regarding the statements, they seem to be a mix of assignments and invocations. One thing to note is that currently, nested invocations aren't stored in a nested manner. For instance, the code `cfg => cfg.AddMaps(Assembly.GetAssembly(typeof(HomeController)))` is broken down into three separate invocations: `addMaps`, `GetAssembly`, and `typeof`. This design choice was based on my use cases where I primarily wanted to identify which code was being called, rather than its exact structure within a single line.

To better assist you, could you provide more specifics on the information you're trying to extract? Sharing the original constructor code as an example would be especially helpful.

**Comment by SirBillofLane** [comment]
This controller represents a better example. Some items are injected but I also initialize others. This is a football pool application closely aligned with the NFL games and structure. The _currentWeek calls a service to query the database.  Same for the _currentClosedWeek.

**Comment by eNeRGy164** [comment]
Just to make sure I'm on the same page as you: are you looking to see if `_service.GetCurrentWeek()` is specifically calling `MrPixter2019.Services.PixterService.GetCurrentWeek()`, and also wanting to view the statements within that method? Let me know if that's what you're aiming for! 😊

**Comment by SirBillofLane** [comment]
Thank you for you quick response. The attachment shows the 13 statements but I am not able to access any of the specifics of the statements like assignment/invocation. If it’s an assignment I want the Left, Operator, and Right values.

**Comment by eNeRGy164** [comment]
I've put together a simple console application to help illustrate how the analysis could work (for this specific constructor, to also handle `if`, `else`, `switch`, etc. you would require more code).
Here's the code:

```csharp
using LivingDocumentation;
using Newtonsoft.Json;

var fileContents = File.ReadAllText("analysis.txt");
var types = JsonConvert.DeserializeObject<List<TypeDescription>>(fileContents, JsonDefaults.DeserializerSettings())!.ToList();

var type = types.FirstOrDefault("MrPixter2019.Controllers.PickController");
var constructor = type.Constructors.First();

foreach (var statement in constructor.Statements)
{
    Console.WriteLine(AnalyzeStatement(statement));
}

static string AnalyzeStatement(Statement statement)
{
    return statement switch
    {
        InvocationDescription invocation => $"Method '{invocation.Name}' of type '{invocation.ContainingType.ClassName()}' is invoked",
        AssignmentDescription assignment => $"Variable '{assignment.Left}' is assigned with the value '{assignment.Right}'",
    };
}
```

When you run this application, you should expect to see the following output:

```text
Variable '_service' is assigned with the value 'pixterService'
Variable '_aDService' is assigned with the value 'aDService'
Variable '_options' is assigned with the value 'options.Value'
Variable '_currentWeek' is assigned with the value '_service.GetCurrentWeek()'
Method 'GetCurrentWeek' of type 'IPixterService' is invoked
Variable '_currentClosedWeek' is assigned with the value '_service.CurrentClosedWeek()??-1'
Method 'CurrentClosedWeek' of type 'IPixterService' is invoked
Variable '_logger' is assigned with the value 'logger'
Method 'MapperConfiguration' of type 'MapperConfiguration' is invoked
Method 'AddMaps' of type 'IMapperConfigurationExpression' is invoked
Method 'GetAssembly' of type 'Assembly' is invoked
Variable 'mapper' is assigned with the value 'new Mapper(config)'
Method 'Mapper' of type 'Mapper' is invoked
```

I hope this gives you a clearer picture. Let me know if this helps.

**Comment by SirBillofLane** [comment]
Wow, thank you so much for taking the time to provide that example project. It is exactly what I needed to understand how to get the desired information.
I apologize for the delayed response. I was helping another developer. I will close this issue,

Thanks again,

Bill
